app:
  name: "Mutual Friend System"
  version: "1.0.0"
  environment: development
  port: 8080

log:
  level: info
  format: json
  output: stdout

grpc:
  port: 9090
  reflection: true

dynamodb:
  endpoint: "http://localhost:8000"
  region: "us-east-1"
  table_name: "MutualFriendSystem"

rabbitmq:
  url: "amqp://admin:admin123@localhost:5672/"
  exchange:
    name: "friend-events"
    type: "topic"
    durable: true
  queue:
    name: "friend-events-queue"
    durable: true
    routing_key: "friend.*"

elasticsearch:
  url: "http://localhost:9200"
  indices:
    users: "users"
  bulk_size: 100
  flush_interval: "5s"

redis:
  url: "redis://localhost:6379"
  password: ""
  db: 0
  pool_size: 10

cache:
  default_ttl: "3600s"
  friend_list_ttl: "1800s"
  recommendation_ttl: "7200s"

batch:
  size: 1000
  timeout: "2s"
  worker_count: 5
  
recommendation:
  max_results: 50
  min_mutual_friends: 1
  calculation_depth: 2